# Generated by Django 2.2.1 on 2019-06-07 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaster', '0002_auto_20190607_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='time_of_work',
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
