# Generated by Django 2.2.1 on 2019-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaster', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='static/images'),
        ),
    ]
